version: "3.9"

services:
  django_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: >
      daphne -b 0.0.0.0 -p 8000 config.asgi:application

  redis:
    image: redis:7
    ports:
      - "6379:6379"
